<?php

/**
 * ISO 4217 currency codes with a representative country flag emoji and display name,
 * used to populate the currency dropdown on package forms.
 */
return [
    'USD' => ['flag' => '🇺🇸', 'name' => 'US Dollar'],
    'EUR' => ['flag' => '🇪🇺', 'name' => 'Euro'],
    'GBP' => ['flag' => '🇬🇧', 'name' => 'British Pound'],
    'JPY' => ['flag' => '🇯🇵', 'name' => 'Japanese Yen'],
    'CNY' => ['flag' => '🇨🇳', 'name' => 'Chinese Yuan'],
    'INR' => ['flag' => '🇮🇳', 'name' => 'Indian Rupee'],
    'AUD' => ['flag' => '🇦🇺', 'name' => 'Australian Dollar'],
    'CAD' => ['flag' => '🇨🇦', 'name' => 'Canadian Dollar'],
    'CHF' => ['flag' => '🇨🇭', 'name' => 'Swiss Franc'],
    'HKD' => ['flag' => '🇭🇰', 'name' => 'Hong Kong Dollar'],
    'SGD' => ['flag' => '🇸🇬', 'name' => 'Singapore Dollar'],
    'SEK' => ['flag' => '🇸🇪', 'name' => 'Swedish Krona'],
    'NOK' => ['flag' => '🇳🇴', 'name' => 'Norwegian Krone'],
    'DKK' => ['flag' => '🇩🇰', 'name' => 'Danish Krone'],
    'NZD' => ['flag' => '🇳🇿', 'name' => 'New Zealand Dollar'],
    'KRW' => ['flag' => '🇰🇷', 'name' => 'South Korean Won'],
    'MXN' => ['flag' => '🇲🇽', 'name' => 'Mexican Peso'],
    'BRL' => ['flag' => '🇧🇷', 'name' => 'Brazilian Real'],
    'ZAR' => ['flag' => '🇿🇦', 'name' => 'South African Rand'],
    'RUB' => ['flag' => '🇷🇺', 'name' => 'Russian Ruble'],
    'TRY' => ['flag' => '🇹🇷', 'name' => 'Turkish Lira'],
    'AED' => ['flag' => '🇦🇪', 'name' => 'UAE Dirham'],
    'SAR' => ['flag' => '🇸🇦', 'name' => 'Saudi Riyal'],
    'QAR' => ['flag' => '🇶🇦', 'name' => 'Qatari Riyal'],
    'KWD' => ['flag' => '🇰🇼', 'name' => 'Kuwaiti Dinar'],
    'BHD' => ['flag' => '🇧🇭', 'name' => 'Bahraini Dinar'],
    'OMR' => ['flag' => '🇴🇲', 'name' => 'Omani Rial'],
    'JOD' => ['flag' => '🇯🇴', 'name' => 'Jordanian Dinar'],
    'ILS' => ['flag' => '🇮🇱', 'name' => 'Israeli New Shekel'],
    'EGP' => ['flag' => '🇪🇬', 'name' => 'Egyptian Pound'],
    'THB' => ['flag' => '🇹🇭', 'name' => 'Thai Baht'],
    'MYR' => ['flag' => '🇲🇾', 'name' => 'Malaysian Ringgit'],
    'IDR' => ['flag' => '🇮🇩', 'name' => 'Indonesian Rupiah'],
    'PHP' => ['flag' => '🇵🇭', 'name' => 'Philippine Peso'],
    'VND' => ['flag' => '🇻🇳', 'name' => 'Vietnamese Dong'],
    'PKR' => ['flag' => '🇵🇰', 'name' => 'Pakistani Rupee'],
    'BDT' => ['flag' => '🇧🇩', 'name' => 'Bangladeshi Taka'],
    'LKR' => ['flag' => '🇱🇰', 'name' => 'Sri Lankan Rupee'],
    'NPR' => ['flag' => '🇳🇵', 'name' => 'Nepalese Rupee'],
    'MMK' => ['flag' => '🇲🇲', 'name' => 'Myanmar Kyat'],
    'KHR' => ['flag' => '🇰🇭', 'name' => 'Cambodian Riel'],
    'LAK' => ['flag' => '🇱🇦', 'name' => 'Lao Kip'],
    'BND' => ['flag' => '🇧🇳', 'name' => 'Brunei Dollar'],
    'TWD' => ['flag' => '🇹🇼', 'name' => 'New Taiwan Dollar'],
    'MOP' => ['flag' => '🇲🇴', 'name' => 'Macanese Pataca'],
    'MNT' => ['flag' => '🇲🇳', 'name' => 'Mongolian Tugrik'],
    'KZT' => ['flag' => '🇰🇿', 'name' => 'Kazakhstani Tenge'],
    'UZS' => ['flag' => '🇺🇿', 'name' => 'Uzbekistani Som'],
    'GEL' => ['flag' => '🇬🇪', 'name' => 'Georgian Lari'],
    'AMD' => ['flag' => '🇦🇲', 'name' => 'Armenian Dram'],
    'AZN' => ['flag' => '🇦🇿', 'name' => 'Azerbaijani Manat'],
    'PLN' => ['flag' => '🇵🇱', 'name' => 'Polish Zloty'],
    'CZK' => ['flag' => '🇨🇿', 'name' => 'Czech Koruna'],
    'HUF' => ['flag' => '🇭🇺', 'name' => 'Hungarian Forint'],
    'RON' => ['flag' => '🇷🇴', 'name' => 'Romanian Leu'],
    'BGN' => ['flag' => '🇧🇬', 'name' => 'Bulgarian Lev'],
    'HRK' => ['flag' => '🇭🇷', 'name' => 'Croatian Kuna'],
    'RSD' => ['flag' => '🇷🇸', 'name' => 'Serbian Dinar'],
    'UAH' => ['flag' => '🇺🇦', 'name' => 'Ukrainian Hryvnia'],
    'ISK' => ['flag' => '🇮🇸', 'name' => 'Icelandic Krona'],
    'ALL' => ['flag' => '🇦🇱', 'name' => 'Albanian Lek'],
    'MKD' => ['flag' => '🇲🇰', 'name' => 'Macedonian Denar'],
    'BAM' => ['flag' => '🇧🇦', 'name' => 'Bosnia-Herzegovina Mark'],
    'MDL' => ['flag' => '🇲🇩', 'name' => 'Moldovan Leu'],
    'BYN' => ['flag' => '🇧🇾', 'name' => 'Belarusian Ruble'],
    'NGN' => ['flag' => '🇳🇬', 'name' => 'Nigerian Naira'],
    'GHS' => ['flag' => '🇬🇭', 'name' => 'Ghanaian Cedi'],
    'KES' => ['flag' => '🇰🇪', 'name' => 'Kenyan Shilling'],
    'TZS' => ['flag' => '🇹🇿', 'name' => 'Tanzanian Shilling'],
    'UGX' => ['flag' => '🇺🇬', 'name' => 'Ugandan Shilling'],
    'ETB' => ['flag' => '🇪🇹', 'name' => 'Ethiopian Birr'],
    'RWF' => ['flag' => '🇷🇼', 'name' => 'Rwandan Franc'],
    'ZMW' => ['flag' => '🇿🇲', 'name' => 'Zambian Kwacha'],
    'MAD' => ['flag' => '🇲🇦', 'name' => 'Moroccan Dirham'],
    'DZD' => ['flag' => '🇩🇿', 'name' => 'Algerian Dinar'],
    'TND' => ['flag' => '🇹🇳', 'name' => 'Tunisian Dinar'],
    'XOF' => ['flag' => '🇸🇳', 'name' => 'West African CFA Franc'],
    'XAF' => ['flag' => '🇨🇲', 'name' => 'Central African CFA Franc'],
    'NAD' => ['flag' => '🇳🇦', 'name' => 'Namibian Dollar'],
    'BWP' => ['flag' => '🇧🇼', 'name' => 'Botswana Pula'],
    'MUR' => ['flag' => '🇲🇺', 'name' => 'Mauritian Rupee'],
    'SCR' => ['flag' => '🇸🇨', 'name' => 'Seychellois Rupee'],
    'ARS' => ['flag' => '🇦🇷', 'name' => 'Argentine Peso'],
    'CLP' => ['flag' => '🇨🇱', 'name' => 'Chilean Peso'],
    'COP' => ['flag' => '🇨🇴', 'name' => 'Colombian Peso'],
    'PEN' => ['flag' => '🇵🇪', 'name' => 'Peruvian Sol'],
    'UYU' => ['flag' => '🇺🇾', 'name' => 'Uruguayan Peso'],
    'BOB' => ['flag' => '🇧🇴', 'name' => 'Bolivian Boliviano'],
    'PYG' => ['flag' => '🇵🇾', 'name' => 'Paraguayan Guarani'],
    'VES' => ['flag' => '🇻🇪', 'name' => 'Venezuelan Bolivar'],
    'GTQ' => ['flag' => '🇬🇹', 'name' => 'Guatemalan Quetzal'],
    'CRC' => ['flag' => '🇨🇷', 'name' => 'Costa Rican Colon'],
    'DOP' => ['flag' => '🇩🇴', 'name' => 'Dominican Peso'],
    'JMD' => ['flag' => '🇯🇲', 'name' => 'Jamaican Dollar'],
    'TTD' => ['flag' => '🇹🇹', 'name' => 'Trinidad & Tobago Dollar'],
    'BSD' => ['flag' => '🇧🇸', 'name' => 'Bahamian Dollar'],
    'BBD' => ['flag' => '🇧🇧', 'name' => 'Barbadian Dollar'],
    'HNL' => ['flag' => '🇭🇳', 'name' => 'Honduran Lempira'],
    'NIO' => ['flag' => '🇳🇮', 'name' => 'Nicaraguan Cordoba'],
    'PAB' => ['flag' => '🇵🇦', 'name' => 'Panamanian Balboa'],
    'FJD' => ['flag' => '🇫🇯', 'name' => 'Fijian Dollar'],
    'PGK' => ['flag' => '🇵🇬', 'name' => 'Papua New Guinean Kina'],
    'WST' => ['flag' => '🇼🇸', 'name' => 'Samoan Tala'],
    'TOP' => ['flag' => '🇹🇴', 'name' => 'Tongan Paanga'],
    'XPF' => ['flag' => '🇵🇫', 'name' => 'CFP Franc'],
    'IRR' => ['flag' => '🇮🇷', 'name' => 'Iranian Rial'],
    'IQD' => ['flag' => '🇮🇶', 'name' => 'Iraqi Dinar'],
    'AFN' => ['flag' => '🇦🇫', 'name' => 'Afghan Afghani'],
    'LBP' => ['flag' => '🇱🇧', 'name' => 'Lebanese Pound'],
    'SYP' => ['flag' => '🇸🇾', 'name' => 'Syrian Pound'],
    'YER' => ['flag' => '🇾🇪', 'name' => 'Yemeni Rial'],
];
